### PR TITLE
feat!: Add support for `network_access_control`, updated minimum supported version of Terraform to `1.0` and AWS provider to `5.0`

### LINKED ISSUE #22: Add network_access_control as an optional configuration to the module to create workspace with restricted access
## Is your request related to a new offering from AWS? 
  - No
## Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅: please list the AWS provider version which introduced this functionality 
 aws provider 4.58.0. https://registry.terraform.io/providers/hashicorp/aws/4.58.0/docs/resources/grafana_workspace

## Is your request related to a problem? Please describe.

 - No, its not a problem , its just that currently the module will always create a workspace with open public access , and I have to manuallly assign the vpc endpoint I have created to it.

## Describe the solution you'd like.

I saw that the resource grafana_workspace can optionaly accept [network_access_control](https://registry.terraform.io/providers/hashicorp/aws/4.58.0/docs/resources/grafana_workspace#network_access_control) and I was wondering if this can be requested as a feature request to the managed_grafana_module to accept it optionally so that I can initialize the workspace with restricted access instead of manually changing it. 

## Describe alternatives you've considered.

I have been tried only one alternative solution and that is to assigning a VPC endpoint manually to the grafana workspace after I create it with terraform with open access.

## Additional context

I have been playing around with the module and I came to the use case where I want to create the workspace with a vpc endpoint so that upon creation it is in a private subnet behind a VPN

### PR DESCRIPTION
**Pull request by bryantbiggs**
## Description
- Add support for `network_access_control`
- Order arguments to align with provider to make comparison easier (sorry for the whitespace noise!)
- Update minimum supported version of Terraform to 1.0
- Update minimum supported version of AWS provider to 5.0

## Motivation and Context
- Resolves #22
- Resolves #23

## Breaking Changes
- Yes; Terraform and provider MSV have changed

## How Has This Been Tested?
- [ ] I have updated at least one of the `examples/*` to demonstrate and validate my change(s)
- [ ] I have tested and validated these changes using one or more of the provided `examples/*` projects

- [x] I have executed `pre-commit run -a` on my pull request

### CODE REVIEW

**Review by antonbabenko — COMMENTED** [review]
Maybe `versions.tf` in the root dir should also be updated to require Terraform `>= 1.0`? And then this PR should become a major release (update title to `feat!: ...`)?

**Comment by bryantbiggs** [comment]
@antonbabenko if you get a moment to 👀

**Review by antonbabenko — APPROVED** [review]
Perfect 👍

**Comment by antonbabenko** [comment]
This PR is included in version 2.0.0 :tada:

**Pull request merged**
